language: node_js
os: linux
env:
  - NPM_SCRIPT=test:browserless
jobs:
  include:
    - name: "(Browser Tests) Full Build For Chrome & Firefox"
      node_js: "12"
      env:
        - NPM_SCRIPT="test:browser"
        - BROWSERS="ChromeHeadless,FirefoxHeadless"
      addons:
        chrome: stable
        firefox: latest
    - name: (Browser Tests) Slim Build For Chrome"
      node_js: "12"
      env:
        - NPM_SCRIPT="test:slim"
        - BROWSERS="ChromeHeadless"
      addons:
        chrome: stable
    - name: "(Browser Tests) No Deps build For Chrome"
      node_js: "12"
      env:
        - NPM_SCRIPT="test:no-deprecated"
        - BROWSERS="ChromeHeadless"
      addons:
        chrome: stable
    - name: "(Browser Tests) ES Build For Chrome"
      node_js: "12"
      env:
        - NPM_SCRIPT="test:esmodules"
        - BROWSERS="ChromeHeadless"
      addons:
        chrome: stable
    - name: "(Browser Tests) AMD Build For Chrome"
      node_js: "12"
      env:
        - NPM_SCRIPT="test:amd"
        - BROWSERS="ChromeHeadless"
      addons:
        chrome: stable
    - name: "(Browser Tests) Full Build For Firefox"
      node_js: "12"
      env:
        - NPM_SCRIPT="test:browser"
        - BROWSERS="FirefoxHeadless"
      addons:
        firefox: latest-esr
